<?php

function hello_user_menu() {
  $items = array();
  $items['user_created'] = array(
    'title' => 'Success!',
    'page callback' => 'successful_add',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function successful_add() {
  if(check_if_admin()) {
    return "<p>You've successfully added a new user!</p>";
  } else {
    return "<p>Thanks for creating an account!</p>";
  }
}

function hello_user_user_insert() {
  $_GET['destination'] = 'user_created';
}

function check_if_admin() {
  global $user;
  if(in_array('administrator', $user->roles)) {
    return TRUE;
  }
  return FALSE;
}
